<?php

declare(strict_types=1);

namespace HDNET\CustomShortcut\Overrides;

class PageRepository extends \TYPO3\CMS\Frontend\Page\PageRepository
{
    public function getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration = 20, $pageLog = [], $disableGroupCheck = false)
    {
        // Todo implement
        return parent::getPageShortcut($shortcutFieldValue, $shortcutMode, $thisUid, $iteration, $pageLog, $disableGroupCheck); // TODO: Change the autogenerated stub
    }
}
