services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HDNET\CustomShortcut\:
    resource: '../Classes/*'
    exclude: [
        '../Classes/Domain/Model/*',
        '../Classes/Overrides/*'
    ]
